### ISSUE TITLE
Design MVP Component Set

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#24]
* Devices Table
* Access Codes Table
* Device View
* Access Code View

**Comment by miken-seam** [comment]
Here's the figma doc for [v1 of prebuilt components](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Out-of-the-box-Components?node-id=258%3A26284&t=PWum7wO5TzX1RQFR-1)

The relevant 3 figma pages:
- ***Design Spec MVP
- ***Prototypes
- ***Components


<img width="271" alt="image" src="https://user-images.githubusercontent.com/112443289/234936365-358c37bd-5b8c-41d3-8689-ac7515ee3293.png">

### What's in each page?

### Design spec
This is the place to start. The spec breaks down the design into basic parts with explanations of general behavior of the main components. 

### Prototypes
An interactive figma prototype is assembled in a page like this one. A prototype is a way to demo the parts of the design and how users navigate and generally interact with them. The page contains steps in the prototype, but you have to "present" or "play" the prototype to view the interactive prototype.

Since the page is really there just to serve the prototype, viewing the page itself can be confusing because the content of the page isn't organized for viewing on the page. The page is basically a script for the prototype.

There's a play button in the upper right of the figma chrome next to the share button that will present a prototype, but a figma page can contain more than one prototype, so it's better to switch to the "Prototype" tab in the upper right.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/112443289/234939041-85f6611b-dad1-4afe-8bef-cc7ec0c11172.png">

Once you switch to the prototype tab, you can see present buttons for different **prototype flows**. You can click the present button for each of those

<img width="294" alt="image" src="https://user-images.githubusercontent.com/112443289/234941095-99e10761-f939-492e-a342-e08909a99197.png">

### Components
This page contains **figma components** which are used in assembling figma mockups. Unfortunately, the term "component" is overloaded and can get confused with items in the design that are meant by design to be viewed as components.

The page called Components holds the **figma components** that are used to build the elements used on the Spec page and in the prototype. These components can be broken down into such small nested parts that it's hard to tell how things fit together. That's why there is a spec page, which is meant to be more easily read.

Figma components are useful if you want to see things like button states, etc. because every variant of that component is defined in an interactive component. In figma an interactive component has a dashed line around it. They usually contain different states or styles of the same element, that can be swapped out in a design, like a button in hover state vs a button in "loading" state.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/112443289/234943653-76d42eca-3e5a-4a3e-8251-7079d44c026f.png">

Components have purple outlines when they're selected. When viewing the "Inspect" tab view, clicking on an icon next to the component's name will take you to the "main component" which is where the component is defined. The main component is usually put in a page that contains components, but they can be anywhere in the figma doc. Clicking on "Go to main component" will take you to wherever that component lives. If the component is an interactive component, it will have multiple variants with different states or styling, etc.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/112443289/234945341-2b10d47e-8ac1-4c54-9dba-c5a95f880a98.png">

So, in general, start with the spec page and present prototypes or drill into components as needed.

@dawnho @seveibar @mikewuu
