### ISSUE TITLE
Table views cutoff on mobile

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#450]
These are for Galaxy S21 size.

How can we support this width?

![image](https://github.com/seamapi/react/assets/721372/c83c10b1-e6c5-433d-9db5-dc60354e19b9)
![image](https://github.com/seamapi/react/assets/721372/6c2f0be1-1400-4cc4-8e68-9a69b0ea4413)
![image](https://github.com/seamapi/react/assets/721372/adb2bd28-0809-4135-96b9-b12b280cf6d3)

**Comment by miken-seam** [comment]
I see 2 issues here:
1. **The list items don't hold up at small sizes.** Part of this is due to padding added by the integrator. Part of it is the design just barely fits at 360 which is the min width they were designed for. Even though 360 is a reasonable minimum width, I think we can make these items more tolerant of smaller widths. But we should still tell our customers that they shouldn't put the components in containers smaller than 360 pixels wide.

2. **The list header should be stacked at small sizes**. There's a component design for a stacked header because there's just not enough horizontal space to fit the title, item count, search box, and add button in the small size (360-449 px).

Generally, I think we can make lists work better without breaking too bad even below 300 px, but it may take some design tweaking. We should probably do it just to make the components more robust overall

For the access code list specifically, I listed out some changes in [this figma page](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=2384-111787&mode=design&t=aedaBBXDvInRPwqa-4) that will keep it working below 360.

I have to look deeper into the other lists: Devices, Thermostats, THemo Schedules, etc, but I thought the small sized versions should be fitting better than they are in the grab. Not sure if we're just seeing the medium or large sizes where the small sizes should be, or what.

I will clean up all the component lists figma files. I noticed some items got changed in some of the lists. Not sure what's causing this but I will start a new page or figma file to keep as the source of truth.

<img width="1127" alt="image" src="https://github.com/seamapi/react/assets/112443289/99eabb38-8675-44e5-892e-6151089c21c3">

https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=2384-111787&mode=design&t=aedaBBXDvInRPwqa-4
